name: build-exe

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Install pipenv
        run: pipx install pipenv
      
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      
      - name: Setup environment
        run: pipenv install
      
      - name: Build the executable using cx_freeze
        run: pipenv run python ./cxfreeze_setup.py build -b win64

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: gparch_cli_win64
          path: win64
          retention-days: 7
      
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Install pipenv
        run: pipx install pipenv
      
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      
      - name: Setup environment
        run: pipenv install
      
      - name: Build the executable using cx_freeze
        run: pipenv run python ./cxfreeze_setup.py build -b linux

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: gparch_cli_linux
          path: linux
          retention-days: 7
      
  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Install pipenv
        run: pipx install pipenv
      
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      
      - name: Setup environment
        run: pipenv install
      
      - name: Build the executable using cx_freeze
        run: pipenv run python ./cxfreeze_setup.py build -b macos

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: gparch_cli_macos
          path: macos
          retention-days: 7
